<?
/*
* Maintenance script (called via cron) that trims the daily edits table. For now we keep a week lookback
* Daily edits table rows are generated by extensions/wikihow/DailyEdits.class.php
*/
require_once('commandLine.inc');

trimDailyEdits();

function trimDailyEdits() {
	$trimDate = strtotime('-7 day', strtotime(date('Ymd', time())));
	$trimDate = wfTimestamp(TS_MW, $trimDate);
	echo "Trimming daily edits with timestamps older than $trimDate\n";
	$dbw = wfGetDB(DB_MASTER);
	$dbw->delete('daily_edits', array("de_timestamp < '$trimDate'"), __METHOD__);
	echo "Finished trimming daily edits table\n";
}
